services:
  db:
    image: postgres:16
    container_name: db_postgres
    environment:
      POSTGRES_DB: pin_desk
      POSTGRES_USER: pin
      POSTGRES_PASSWORD: pin
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./Source
    container_name: backend
    restart: always
    depends_on:
      - db
    env_file:
      - ./Source/.env
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    image: nginx:alpine
    container_name: frontend
    restart: always
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
