spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED}

logging:
  level:
    org.springframework.boot.context.config: DEBUG
    org.flywaydb: INFO
    org.springframework.jdbc.core: DEBUG
    ru.itmo.pindesk: DEBUG

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    ttlMinutes: ${APP_JWT_TTL_MINUTES}